from aiogram.types import ReplyKeyboardMarkup, KeyboardButton

add_album_btn = KeyboardButton('Создать альбом 🖼')
edit_album_btn = KeyboardButton('Редактировать альбом 👩‍🎨')
delete_album_btn = KeyboardButton('Удалить альбом ❌')
add_photo_btn = KeyboardButton('Добавить фото 📸')
delete_photo = KeyboardButton('Удалить фото ❌')
#show_album_btn = KeyboardButton('Показать все альбомы 🎞')
#show_all_photo_btn = KeyboardButton('Показать все фото 🎞')
show_photo_btn = KeyboardButton('Фото 📸')
my_events = KeyboardButton('Мероприятия 🎫')
create_event_btn = KeyboardButton('Создать мероприятие 👩‍🏫')
edit_event_btn = KeyboardButton('Редактировать мероприятие 📝')
create_newsletter_btn = KeyboardButton('Создать новую рассылку 🗞')
user_list_btn = KeyboardButton('Вывести список пользователей 👥')
clients_btn = KeyboardButton('Клавиатура клиента 👨‍💻')

admin_kb = ReplyKeyboardMarkup()
admin_kb.add(add_album_btn, edit_album_btn, delete_album_btn)
admin_kb.add(add_photo_btn, delete_photo)
admin_kb.add(my_events, create_event_btn, edit_event_btn)
admin_kb.add(create_newsletter_btn)
admin_kb.add(user_list_btn)
admin_kb.add(clients_btn)